### ISSUE TITLE
Only works in node version 10.15.3, crashes on the latest version (11.14.0)

### ISSUE THREAD

**Issue by JamesGDiaz** [tamasszoke/mern-seed#1]
I set up the boilerplate on node version 11 and everything compiles and runs correctly, except until I click anything on the client, the server crashes with this error:

>  internal/buffer.js:788
> class FastBuffer extends Uint8Array {}
> ^
> 
> RangeError: Invalid typed array length: -4095
>     at new Uint8Array (<anonymous>)
>     at new FastBuffer (internal/buffer.js:788:1)
>     at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:149:17)
>     at Stream.<anonymous> (/home/james/Desktop/confettibot-mern/server/node_modules/handle-thing/lib/handle.js:88:10)
>     at Stream.emit (events.js:198:15)
>     at endReadableNT (/home/james/Desktop/confettibot-mern/server/node_modules/readable-stream/lib/_stream_readable.js:1077:12)

This is a bug in V8 I think (see https://github.com/nodejs/node/issues/24097)
But maybe there is something wrong in your code that fires this bug.

Thanks

**Comment by tamasszoke** [comment]
I have checked the issue, it seems like the **spdy** module causes it, check this [discussion](https://github.com/spdy-http2/node-spdy/issues/350). According to this, it won't be fixed, their suggestion is to use the native HTTP2 module instead, which is in Node v10+. But there's a catch, the HTTP module does not work with Express 4, see this [discussion](https://github.com/expressjs/express/pull/3730), it will be resolved only in Express 5.

According to this, if you want to use it with Node v11 you should use regular HTTP or HTTPS. Another option is to use the HTTP/HTTPS server with a NGINX HTTP2 proxy. With HTTP2, the recommended way is to use Node v10, at least until the Express 5 releases.

**Comment by JamesGDiaz** [comment]
Thank you, I think we can close this issue.
By the way this boilerplate is amazing. It has saved me hours and hours of work. Thank you very much
