### ISSUE TITLE
.env files

### ISSUE THREAD

**Issue by zafrirron** [tamasszoke/mern-seed#47]

**Comment by tamasszoke** [comment]
Ignoring `.env` files in the project by default is a security feature, so future users won't accidentally leak their sensitive information. They can only do it on purpose by changing the `.gitignore` files.

I'm not changing this, but you can always fork it and modify it for your needs.

**Comment by zafrirron** [comment]
It ok! thanks just noticed you are creating the files in setup.sh, usually you could just put a env_sample template file to be used...
